
RUN apt-get update && apt-get install -y \
	dumb-init

ADD default_project /home/coder/project
WORKDIR /home/coder/project

# This assures we have a volume mounted even if the user forgot to do bind mount.
# So that they do not lose their data if they delete the container.
VOLUME [ "/home/coder/project" ]

COPY --from=codercom/code-server:latest /usr/local/bin/code-server /usr/local/bin/code-server

EXPOSE 8443

