
linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

matrix:
  include:
    - <<: *linux
      addons:
        apt:
          update: true
          packages:
            - docker-ce
            - cmake
            - ninja
            - clang

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - cmake --build .
