os: linux
dist: xenial
sudo: required
language: python
python: "3.6"
addons:
  apt:
    update: true
    packages:
      - docker-ce
      - ninja
      - clang
services:
  - docker

before_install:
  - sudo apt-get remove cmake
  - sudo apt purge --auto-remove cmake

install:
  - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Linux-x86_64.sh -o /tmp/cmake.sh
  - sudo bash /tmp/cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - cmake --build .
