os: linux
dist: xenial
sudo: required
language: python
python: "3.6"
addons:
  apt:
    update: true
    packages:
      - docker-ce
      - ninja-build
      - clang
      - cmake

services:
  - docker

script:
  - mkdir build && cd build
  - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -G Ninja ..
  - ninja Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ninja Upload
