
linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

matrix:
  include:
    - <<: *linux

install:
  - apt-get update && apt-get -y install cmake ninja clang

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - cmake --build .
