os: linux
dist: xenial
sudo: required
language: python
python: "3.6"
addons:
  apt:
    update: true
    packages:
      - docker-ce
      - ninja
      - clang
      - cmake

services:
  - docker

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - cmake --build .
